### ISSUE TITLE
URL of pretrained SiTPose(light version) is broken

### ISSUE THREAD

**Issue by ngoivanessa** [lktidaohuoxing/SiTPose#1]
In the test demo section, there is a google drive link provided to the pretrained model of SiTPose (light version). However, when clicked, it says that the file does not exist (refer to screenshot below). 

Can an updated link be provided? Thank you.

![Screenshot 2023-06-23 at 11 57 58 AM](https://github.com/lktidaohuoxing/SiTPose/assets/66506035/12e4640b-5000-4a5c-95fc-4478083796d2)

**Comment by lktidaohuoxing** [comment]
Sorry, I accidentally deleted it in the process of cleaning up the file before, I will upload it in the last two days.

**Comment by lktidaohuoxing** [comment]
You can also train a version yourself on your own dataset

**Comment by lktidaohuoxing** [comment]
fixed
